// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB1e6poNQSlIpxqay9aCYiHyUdMwKwcF8',
    appId: '1:451521418835:web:692afcc7dfd04ac56bd8a6',
    messagingSenderId: '451521418835',
    projectId: 'sportbooking-26310',
    authDomain: 'sportbooking-26310.firebaseapp.com',
    storageBucket: 'sportbooking-26310.firebasestorage.app',
    measurementId: 'G-FF0F76907F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKKB-fvshe3F5CsX8ZfwBzkyPyOQy7Bqw',
    appId: '1:451521418835:android:4fff7282f764aa9d6bd8a6',
    messagingSenderId: '451521418835',
    projectId: 'sportbooking-26310',
    storageBucket: 'sportbooking-26310.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCZEukc2JS_vMqLxu_tE966hpQ2sed3Ig',
    appId: '1:451521418835:ios:b57d4f48afcdbbe36bd8a6',
    messagingSenderId: '451521418835',
    projectId: 'sportbooking-26310',
    storageBucket: 'sportbooking-26310.firebasestorage.app',
    iosClientId: '451521418835-na7pvhpac5vso3mgmek487g98mtptf3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCZEukc2JS_vMqLxu_tE966hpQ2sed3Ig',
    appId: '1:451521418835:ios:b57d4f48afcdbbe36bd8a6',
    messagingSenderId: '451521418835',
    projectId: 'sportbooking-26310',
    storageBucket: 'sportbooking-26310.firebasestorage.app',
    iosClientId: '451521418835-na7pvhpac5vso3mgmek487g98mtptf3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB1e6poNQSlIpxqay9aCYiHyUdMwKwcF8',
    appId: '1:451521418835:web:14248bf08a89823b6bd8a6',
    messagingSenderId: '451521418835',
    projectId: 'sportbooking-26310',
    authDomain: 'sportbooking-26310.firebaseapp.com',
    storageBucket: 'sportbooking-26310.firebasestorage.app',
    measurementId: 'G-YKPN12JCBL',
  );
}
